### ISSUE TITLE
What does the method gf_getCanvas actually return?

### ISSUE THREAD

**Issue by 0u812** [sys-bio/sbnw#10]
_From @hsauro on October 22, 2015 2:54_

The docs says that the method  gf_canvas gf_getCanvas returns a canvas, but what is this canvas? gf_canvas appears to be a void*. The docs are unclear in this matter.

_Copied from original issue: 0u812/sbnw#45_

**Comment by 0u812** [comment]
It's a drawing canvas. Width/height can be get/set:
gf_canvGetWidth
gf_canvGetHeight
gf_canvSetWidth
gf_canvSetHeight
All of those methods are documented so I think I can close this, please let me know otherwise.

**Comment by hsauro** [comment]
When I click on g_canvas in say gf_getCanvas, the docs just give void
*canv, there is nothing else to suggest what it might be. You should add an
explanation of what canvas is in the gf_canvas struct reference. I had not
idea that canvas had information non the width etc.

H

**Comment by 0u812** [comment]
Good point, I should document the types too.
