### ISSUE TITLE
Possible to change node distance without forcing a relayout?

### ISSUE THREAD

**Issue by 0u812** [sys-bio/sbnw#15]
_From @hsauro on October 22, 2015 0:24_

Is it possible to change the node distance without forcing the library to recompute a new layout?

_Copied from original issue: 0u812/sbnw#40_

**Comment by 0u812** [comment]
The node distance parameter of the layout engine is used by the FR algorithm to control the strength of repulsive forces, so you would have to re-run the algorithm if you changed it. You could scale the centroid coordinates of nodes and reactions to sort of achieve the effect of changing node spacing, but the FR algorithm produces much nicer layouts, so why not just re-run the FR algorithm?

**Comment by hsauro** [comment]
Because it goes a completely different layout the second it is run.

H

**Comment by 0u812** [comment]
You can lock the nodes you don't want to move.

On October 23, 2015 12:23:05 PM PDT, Herbert Sauro <notifications@github.com> wrote:
>Because it goes a completely different layout the second it is run.
>
>H
>
>
>On Fri, Oct 23, 2015 at 10:49 AM, Kyle Medley
><notifications@github.com>
>wrote:
>
>> The node distance parameter of the layout engine is used by the FR
>> algorithm to control the strength of repulsive forces, so you would
>have to
>> re-run the algorithm if you changed it. You could scale the centroid
>> coordinates of nodes and reactions to sort of achieve the effect of
>> changing node spacing, but the FR algorithm produces much nicer
>layouts, so
>> why not just re-run the FR algorithm?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/sys-bio/sbnw/issues/15#issuecomment-150645064>.
>>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/sys-bio/sbnw/issues/15#issuecomment-150668774

-- 
Sent from my TARDIS with K-9 Mail. Wibbly-wobbly wordy gurdy.

**Comment by 0u812** [comment]
Another option is to disable `prerandomize` in [fr_options](http://sys-bio.github.io/sbnw/docs/struct____fr__options.html), which should allow the nodes to keep their current positions during layout. The network can still move, though. I'm not sure if it's the effect you want.
