### ISSUE TITLE
Version 1.3.4 is buggy

### ISSUE THREAD

**Issue by kirichoi** [sys-bio/sbnw#30]
Version 1.3.4 creates visual artifacts, misses arrows and regulators when color is specified.

**Comment by 0u812** [comment]
Regulator color is specified via setRegulatorColor.

On October 27, 2015 12:25:16 PM PDT, Kiri Choi <notifications@github.com> wrote:
>Version 1.3.4 creates visual artifacts, misses arrows and regulators
>when color is specified.
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/sys-bio/sbnw/issues/30

-- 
Sent from my TARDIS with K-9 Mail. Wibbly-wobbly wordy gurdy.

**Comment by 0u812** [comment]
Resolved
