### ISSUE TITLE
Its not possible to change the Id of the default unit volume

### ISSUE THREAD

**Issue by hsauro** [sys-bio/sbnw#33]
Currently the default volume of unit volume has a hardcoded id, that is graphfab_default_compartment. There should be a setDefaultCompartmentId method to allow users to change the default name.

**Comment by 0u812** [comment]
Two new methods:
get:
http://sys-bio.github.io/sbnw/docs/group__C__API.html#gaf7feb91f4f5ae2abe846d12d087937f5
set:
http://sys-bio.github.io/sbnw/docs/group__C__API.html#ga1cdf0b35f047296ef88a6d842784fa67
