### ISSUE TITLE
Bug in retrieving SBML after loading SBML

### ISSUE THREAD

**Issue by hsauro** [sys-bio/sbnw#35]
Might be a but in retrieving getSBMLLayout function. Load SBML and call doLayout then retrieve SBML via gf_getSBMLWithLayout. It looks like the method does not assign a model id to the sbml which makes the sbml invalid. An id is passed to the library when the library is loaded.

**Comment by 0u812** [comment]
Added:
set id:
http://sys-bio.github.io/sbnw/docs/group__C__API.html#ga083fa5aef06d94e6f07acff8cdd90d99

get id:
http://sys-bio.github.io/sbnw/docs/group__C__API.html#ga3f06f0427792a487e1cfbb583643bdce

**Comment by 0u812** [comment]
Id should now be properly serialized.

**Comment by 0u812** [comment]
Binaries with the fix are here:
https://sourceforge.net/projects/sbnw/files/1.3.9
