### ISSUE TITLE
getNumComps returns 0 if the only compartment is the default one.

### ISSUE THREAD

**Issue by hsauro** [sys-bio/sbnw#37]
When I get gf_nw_getNumComps it seems to return a zero even though the model has a default compartment, is this expected behavior? If so how do I identify the default compartment?

**Comment by 0u812** [comment]
It was just a workaround to support SBML. It's created on-the-fly when writing the SBML and elided when reading the SBML. It never exists when the model is loaded in memory.

**Comment by hsauro** [comment]
So returning 0 is expected behavior?

**Comment by 0u812** [comment]
Correct
