### ISSUE TITLE
Check whether gf_compartment_getID works.

### ISSUE THREAD

**Issue by hsauro** [sys-bio/sbnw#38]
I am getting and access violation when I call gf_compartment_getID, The compartment ptr seems ok. The model I have has three compartments, I am using the get compartment call on index 0 to get the compartment ptr then calling gf_compartment_getID  with that ptr.

Currently running 1.3.9

H

**Comment by 0u812** [comment]
I think the pointer must be bad. Just added more runtime type checking:
https://sourceforge.net/projects/sbnw/files/1.3.12

If that doesn't work, can you send me the model?

**Comment by 0u812** [comment]
Btw calling gf_haveError right after gf_compartment_getID tells you if there was an error or not.

**Comment by hsauro** [comment]
It doesn't crash anymore but it returns an empty string, no Id.

**Comment by 0u812** [comment]
Solved on client side, problem was gf_compartment struct was being passed where pointer was expected.
