### ISSUE TITLE
Network viewer error in updated Spyder with IPython

### ISSUE THREAD

**Issue by kirichoi** [sys-bio/sbnw#42]
In Spyder 2.3.8 with IPython 4.0.3, following error occurs:
```
Traceback (most recent call last):
  File "C:\Tellurium-Winpython\python-2.7.10\lib\site-packages\spyderlib\plugins\externalconsole.py", line 1246, in toggle_view
    self.open_interpreter()
  File "C:\Tellurium-Winpython\python-2.7.10\lib\site-packages\spyderlib\plugins\externalconsole.py", line 1258, in open_interpreter
    interact=True, debug=False, python=True)
  File "C:\Tellurium-Winpython\python-2.7.10\lib\site-packages\spyderplugins\p_pyfab.py", line 274, in start
    sw.notification_thread.layout.connect(self.network_layout)
AttributeError: 'NotificationThread' object has no attribute 'layout'
SBNWExternalConsole start
Traceback (most recent call last):
  File "C:\Tellurium-Winpython\python-2.7.10\lib\site-packages\spyderlib\plugins\ipythonconsole.py", line 656, in toggle_view
    self.create_new_client(give_focus=False)
  File "C:\Tellurium-Winpython\python-2.7.10\lib\site-packages\spyderlib\plugins\ipythonconsole.py", line 832, in create_new_client
    self.main.extconsole.start_ipykernel(client, give_focus=give_focus)
  File "C:\Tellurium-Winpython\python-2.7.10\lib\site-packages\spyderlib\plugins\externalconsole.py", line 1273, in start_ipykernel
    ipyclient=client, give_ipyclient_focus=give_focus)
  File "C:\Tellurium-Winpython\python-2.7.10\lib\site-packages\spyderplugins\p_pyfab.py", line 274, in start
    sw.notification_thread.layout.connect(self.network_layout)
AttributeError: 'NotificationThread' object has no attribute 'layout'
```

**Comment by 0u812** [comment]
That's because you changed the Spyder version. I have said many times that the network viewer requires manual patching.

On January 20, 2016 6:04:48 PM PST, Kiri Choi <notifications@github.com> wrote:
>In Spyder 238 with IPython 403, following error occurs:
>```
>Traceback (most recent call last):
>File
>"C:\Tellurium-Winpython\python-2710\lib\site-packages\spyderlib\plugins\externalconsolepy",
>line 1246, in toggle_view
>    selfopen_interpreter()
>File
>"C:\Tellurium-Winpython\python-2710\lib\site-packages\spyderlib\plugins\externalconsolepy",
>line 1258, in open_interpreter
>    interact=True, debug=False, python=True)
>File
>"C:\Tellurium-Winpython\python-2710\lib\site-packages\spyderplugins\p_pyfabpy",
>line 274, in start
>    swnotification_threadlayoutconnect(selfnetwork_layout)
>AttributeError: 'NotificationThread' object has no attribute 'layout'
>SBNWExternalConsole start
>Traceback (most recent call last):
>File
>"C:\Tellurium-Winpython\python-2710\lib\site-packages\spyderlib\plugins\ipythonconsolepy",
>line 656, in toggle_view
>    selfcreate_new_client(give_focus=False)
>File
>"C:\Tellurium-Winpython\python-2710\lib\site-packages\spyderlib\plugins\ipythonconsolepy",
>line 832, in create_new_client
>    selfmainextconsolestart_ipykernel(client, give_focus=give_focus)
>File
>"C:\Tellurium-Winpython\python-2710\lib\site-packages\spyderlib\plugins\externalconsolepy",
>line 1273, in start_ipykernel
>    ipyclient=client, give_ipyclient_focus=give_focus)
>File
>"C:\Tellurium-Winpython\python-2710\lib\site-packages\spyderplugins\p_pyfabpy",
>line 274, in start
>    swnotification_threadlayoutconnect(selfnetwork_layout)
>AttributeError: 'NotificationThread' object has no attribute 'layout'
>```
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/sys-bio/sbnw/issues/42

-- 
Sent from my TARDIS with K-9 Mail. Wibbly-wobbly wordy gurdy.

**Comment by kirichoi** [comment]
Yeah that's what I just figured out. I might release v0.2 of Windows version of Tellurium with version updates.
