### ISSUE TITLE
Crash with gf_nw_newAliasNodep()

### ISSUE THREAD

**Issue by hsauro** [sys-bio/sbnw#46]
The following sequence of calls to create a node and associated alias node results in an access violation in libsbnw.dll (Windows), version 1.3.23

```
gf_SBMLModel *model = gf_SBMLModel_newp();  // is this call required?
gf_layoutInfo *layout = gf_layoutInfo_newp (2, 4, 1000, 1000);  // success
gf_network *network = gf_getNetworkp (layout);  // success
gf_setDefaultCompartmentId ("compartment");  // returns true
// Create a master (unique) node
gf_node *node = gf_nw_newNodep (network, "Node0", "myNode0", NULL); // success

// next create an alias associated with the node we just created
gf_node *mynode = gf_nw_getUniqueNodep (network, 0); // success, 0 is the node index
gf_node *myalias = gf_nw_newAliasNodep (network, node); // ACCESS VIOLATION HERE
```

**Comment by hsauro** [comment]
Update: I've identified part of the problem in sbnw, you have a method in network.h:

 inline Node* CastToNode(void* p) {
        // **** THIS LINE CAUSES A CRASH
        NetworkElement* e = (NetworkElement*)p; 
        AN(e->hasNetworkElementBase(), "Runtime type check failed");
//         std::cout << typeid((Node&)*e).name() << std::endl;
        AN(dynamic_cast<Node*>(e), "Runtime type check failed");
        return dynamic_cast<Node*>(e);

// This is code you commented out
//         Node* x = (Node*)e;
//         AN(x->doByteCheck(), "Runtime type check failed");
//         return x;
    }


The above method is in turn called by (in layout.cpp)

void gf_node_setIsAlias(gf_node* n, int isAlias) {
    Node* node = CastToNode(n->n);  
etc.

Looks like a node isn't castable to a networkelement?

**Comment by 0u812** [comment]
It looks like you are calling the library correctly. This issue seems to be caused by the fact that I had an explicit check for nodes using the same id. Now that we have aliases, they are supposed to use the same id, so I removed the check. You can find the binaries here:
https://github.com/sys-bio/sbnw/releases/tag/1.3.24

Please let me know if you run into any more trouble. I have a feeling we're not out of the woods yet...

**Comment by hsauro** [comment]
Still get a crash when I call gf_nw_newAliasNodep.

Create one unique node then create an associated alias node and crash. However one thing I noticed is that the version is still 1.3.23,  maybe the old one was released?

**Comment by hsauro** [comment]
Great, I'll give it a go.

H
