### ISSUE TITLE
Does sbwnw work in 1.3.4 (havn't tried in 1.3.5)

### ISSUE THREAD

**Issue by hsauro** [sys-bio/sbnw#55]
When I try to load an sbml file into sbnw, the iewer doesn't show the network, instead it returns an address?

sbnw.loadsbml ('c:\\tmp\\tmp.xml')
Out[32]: <sbnw.sbmlmodel at 0x157f9a10>

**Comment by 0u812** [comment]
Assuming you are trying to load the SBML into the network viewer plugin 
for Tellurium (which is different from using the wrapper to the layout 
library itself as in your example below), here is how to do it (I think 
we had this example in the Tellurium paper at one point but it may have 
been removed):

```

import nwed

nwed.setsbml('...SBML string...')

```

I just tested this on the Mac version of Tellurium and it appears to be 
working fine.

**Comment by 0u812** [comment]
This appears to be working so I'll go ahead and close this.
