### ISSUE TITLE
Summarize difference with these three pointers

### ISSUE THREAD

**Issue by 0u812** [sys-bio/sbnw#8]
_From @hsauro on October 22, 2015 3:14_

Looking through the methods I noticed at least three different kinds of pointers that refer to the model/layout/network, ie

gf_SBMLModel
gf_network
gf_layoutInfo

what is the difference between the three of them, do we need all three of them, could they be consolidated into one pointer to simplify things? In particular the difference between gf_network and gf_layoutInfo isn't clear to me. 

_Copied from original issue: 0u812/sbnw#47_

**Comment by 0u812** [comment]
The layout extension is layered on top of an SBML model, hence the distinction between gf_SBMLModel and gf_layoutInfo. gf_network contains the network coordinates. gf_layoutInfo contains the gf_network as well as canvas info and some SBML settings.

If you don't need anything but the gf_network I could make a convenience function to retrieve it directly from a file name, but all three objects are required by the API.

**Comment by hsauro** [comment]
I'm creating a second layer on top of your API in Delphi to make things a
bit simpler and hide the complexity. I think we'll need something similar
for Python.
